//! Image extraction. Load the image bytes, send them to Ollama's
//! multimedia model with the bundled `extraction-image-describe` prompt,
//! and return a `MediaDocument` of kind `image-text`.

use base64::Engine as _;
use serde_json::{json, Value};

use crate::config::MediaConfig;
use crate::ollama;
use crate::prompt;

pub async fn run_image(
    client: &reqwest::Client,
    bytes: &[u8],
    file_name: Option<&str>,
    cfg: &MediaConfig,
) -> Result<Value, String> {
    let name_hint = file_name.unwrap_or("image");
    let image_metadata = format!(
        "filename: {name}, file_size: {} bytes",
        bytes.len(),
        name = name_hint
    );

    let template = prompt::load("extraction-image-describe.prompt.txt")?;
    let rendered = prompt::render(
        template,
        &[("file_name", name_hint), ("image_metadata", &image_metadata)],
    );

    let image_b64 = base64::engine::general_purpose::STANDARD.encode(bytes);
    let response = ollama::generate_with_image(
        client,
        &cfg.ollama_url,
        &cfg.multimedia_model,
        &rendered,
        &image_b64,
    )
    .await?;

    let parsed = ollama::parse_llm_json(&response).ok_or_else(|| {
        format!(
            "vision model returned non-JSON response (model={}): {response}",
            cfg.multimedia_model
        )
    })?;

    let document_name = parsed
        .get("document_name")
        .and_then(|v| v.as_str())
        .map(str::to_string)
        .unwrap_or_else(|| {
            normalize_document_name(file_name.unwrap_or("image"), "image-text")
        });
    let title = parsed
        .get("title")
        .and_then(|v| v.as_str())
        .map(str::to_string);
    let summary = parsed
        .get("summary")
        .and_then(|v| v.as_str())
        .map(str::to_string);
    let description = parsed
        .get("description")
        .and_then(|v| v.as_str())
        .map(str::to_string);
    let metadata_notes = parsed
        .get("metadata_notes")
        .and_then(|v| v.as_str())
        .map(str::to_string)
        .filter(|s| !s.trim().is_empty());

    let mut notes = vec!["Description generated by vision model".to_string()];
    if let Some(mn) = metadata_notes {
        notes.push(mn);
    }

    let mut contents = json!({});
    if let Some(desc) = &description {
        contents["extracted_text"] = Value::String(desc.clone());
    }
    contents["source_metadata"] = json!({
        "file_name": file_name,
        "image_metadata": image_metadata,
        "model": cfg.multimedia_model,
    });

    let doc = json!({
        "kind": "image-text",
        "document_name": document_name,
        "title": title,
        "summary": summary,
        "author": Value::Null,
        "contents": contents,
        "notes": notes,
    });

    Ok(doc)
}

fn normalize_document_name(input: &str, fallback: &str) -> String {
    let mut out = String::with_capacity(input.len());
    let mut last_dash = false;
    for ch in input.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_lowercase());
            last_dash = false;
        } else if !last_dash {
            out.push('-');
            last_dash = true;
        }
    }
    let trimmed = out.trim_matches('-').to_string();
    if trimmed.is_empty() {
        fallback.to_string()
    } else {
        trimmed
    }
}
